name: Linting with Pylint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Choose the Python version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt

    - name: Run Pylint
      run: |
      # Run Pylint and capture the exit code
        pylint calculus.py || { exit_code=$?; } && { [ $exit_code -eq 1 ] || exit $exit_code; }

        # Check if the exit code is 30 and exit with the same code
        [ $exit_code -eq 30 ] && exit $exit_code || true
